services:
  - type: pserv
    name: docs
    env: python
    region: frankfurt
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run mkdocs serve
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
  - type: web
    name: oauth2-proxy
    env: docker
    plan: starter
    region: frankfurt
    envVars:
      - key: OAUTH2_PROXY_UPSTREAMS
        value: "https://google.com"
        # fromService: 
        #   type: web
        #   name: docs 
        #   envVarKey: RENDER_EXTERNAL_URL
        # fromService:
        #   name: docs
        #   type: web
        #   property: hostport
      - key: OAUTH2_PROXY_PROVIDER
        sync: false
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECRET
        generateValue: true
      - key: OAUTH2_PROXY_EMAIL_DOMAINS
        value: 'accelleran.com'
      - key: OAUTH2_PROXY_HTTP_ADDRESS
        value: ":10000"
